spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://frosaleslillo_db_user:uSmqB36gLzao3ZFZ@discografica-db.btrigbi.mongodb.net/?appName=discografica-db
spring.data.mongodb.database=discografica-db
server.port=${PORT:8080}